import { Award, Printer } from 'lucide-react'
import { calculateStudent, gradeFor, studentRank, subjectTotal } from './GradeCalculator.jsx'

export default function ReportCard({ student, students }) {
  const totals = calculateStudent(student)
  const rank = studentRank(students, student)
  const passedSubjects = student.subjects.filter((subject) => subjectTotal(subject) >= 40).length
  return <article className="report-card">
    <header className="report-heading"><div className="report-seal"><Award size={25} strokeWidth={1.5} /></div><div className="report-school"><p className="report-kicker">Official academic record</p><h1>Riverside Institute of Technology</h1><p>Chennai, Tamil Nadu · Excellence in education</p></div><div className="report-document-meta"><span>ACADEMIC SERVICES</span><strong>EDU · {student.studentId || student.id}</strong><button type="button" className="button button-outline print-button" onClick={() => window.print()}><Printer size={16} /> Print / Save PDF</button></div></header>
    <div className="report-title-bar"><span>STUDENT REPORT CARD</span><span>ACADEMIC YEAR <strong>{student.academicYear}</strong></span></div>
    <section className="report-student-info"><div className="report-student-name"><span>STUDENT NAME</span><strong>{student.name}</strong><small>{student.department || 'Department not specified'}</small></div><div><span>STUDENT ID</span><strong>{student.studentId || student.id}</strong></div><div><span>ROLL NUMBER</span><strong>{student.rollNumber}</strong></div><div><span>CLASS</span><strong>{student.className}</strong></div><div><span>SECTION</span><strong>{student.section}</strong></div><div><span>DATE OF BIRTH</span><strong>{student.dateOfBirth ? new Date(`${student.dateOfBirth}T00:00:00`).toLocaleDateString('en-IN') : '—'}</strong></div></section>
    <div className="report-section-heading"><div><span>01</span><h2>Subject performance</h2></div><small>{student.subjects.length} subjects assessed</small></div>
    <div className="report-table-scroll"><table className="report-table"><thead><tr><th>Subject</th><th>Internal <small>/ 20</small></th><th>Assignment <small>/ 10</small></th><th>Practical <small>/ 20</small></th><th>Theory <small>/ 50</small></th><th>Total <small>/ 100</small></th><th>Grade</th><th>Result</th></tr></thead><tbody>{student.subjects.map((subject, index) => { const total = subjectTotal(subject); return <tr key={`${subject.name}-${index}`}><td>{subject.name}</td><td>{subject.internal}</td><td>{subject.assignment}</td><td>{subject.practical}</td><td>{subject.theory}</td><td className="strong-cell">{total}</td><td><span className="grade-pill">{gradeFor(total)}</span></td><td><span className={`result-text ${total >= 40 ? 'pass' : 'fail'}`}>{total >= 40 ? 'PASS' : 'FAIL'}</span></td></tr> })}</tbody><tfoot><tr><td colSpan="5">Subjects passed</td><td colSpan="3">{passedSubjects} of {student.subjects.length}</td></tr></tfoot></table></div>
    <div className="report-section-heading result-heading"><div><span>02</span><h2>Academic standing</h2></div><small>Calculated from recorded marks</small></div>
    <section className="report-summary"><div className="summary-metric"><span>Total marks</span><strong>{totals.totalMarks}<small> / {totals.maximumMarks}</small></strong></div><div className="summary-metric"><span>Percentage</span><strong>{totals.percentage.toFixed(1)}<small>%</small></strong></div><div className="summary-metric"><span>Average mark</span><strong>{totals.averageMark.toFixed(1)}<small> / 100</small></strong></div><div className="summary-metric"><span>Overall grade</span><strong><span className="grade-pill">{totals.grade}</span></strong></div><div className="summary-metric"><span>Overall result</span><strong className={`result-text ${totals.result === 'PASS' ? 'pass' : 'fail'}`}>{totals.result}</strong></div><div className="summary-metric"><span>Class rank</span><strong>#{rank}</strong></div></section>
    <footer className="report-footer"><div className="signature"><span></span><strong>Class teacher</strong></div><div className="report-date">Date issued<br /><strong>{new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}</strong><small>Computer-generated academic record</small></div><div className="signature"><span></span><strong>Principal</strong></div></footer>
  </article>
}