import { Link, useParams } from 'react-router-dom'
import { ArrowLeft, ClipboardList, FileBadge2, Pencil, UserRound } from 'lucide-react'
import { useStudents } from '../StudentContext.jsx'
import { calculateStudent } from '../components/GradeCalculator.jsx'

export default function StudentDetail() {
  const { id } = useParams()
  const { students } = useStudents()
  const student = students.find((item) => item.id === id)
  if (!student) return <div className="not-found"><h1>Student not found</h1><Link to="/students">Return to students</Link></div>
  const totals = calculateStudent(student)
  return <div className="student-detail-page"><Link to="/students" className="back-link"><ArrowLeft size={16} /> Back to students</Link><div className="student-detail-hero"><div className="student-detail-avatar">{student.name.split(' ').map((part) => part[0]).slice(0, 2).join('')}</div><div><span className="eyebrow"><UserRound size={14} /> STUDENT PROFILE</span><h1>{student.name}</h1><p>{student.studentId || student.id} · Roll no. {student.rollNumber}</p></div><div className="student-detail-actions"><Link to={`/students/${student.id}/edit`} className="button button-outline"><Pencil size={15} /> Edit profile</Link><Link to={`/marks?student=${student.id}`} className="button button-outline"><ClipboardList size={15} /> Enter marks</Link><Link to={`/report/${student.id}`} className="button button-primary"><FileBadge2 size={15} /> Report card</Link></div></div><div className="student-detail-grid"><section className="panel"><div className="panel-heading"><div><h2>Personal & contact</h2><p>Student information</p></div></div><dl className="detail-list">{[['Student ID', student.studentId || student.id], ['Date of birth', student.dateOfBirth || 'Not provided'], ['Gender', student.gender || 'Not provided'], ['Email', student.email || 'Not provided'], ['Mobile', student.phone || 'Not provided'], ['Parent / guardian', student.parentName || 'Not provided'], ['Parent mobile', student.parentPhone || 'Not provided'], ['Address', student.address || 'Not provided']].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section><section className="panel"><div className="panel-heading"><div><h2>Academic record</h2><p>{student.academicYear}</p></div><span className={`status-pill ${totals.result === 'PASS' ? 'status-pass' : 'status-fail'}`}><i />{totals.result}</span></div><dl className="detail-list">{[['Class', student.className], ['Section', student.section], ['Department', student.department], ['Total marks', `${totals.totalMarks} / ${totals.maximumMarks}`], ['Percentage', `${totals.percentage.toFixed(1)}%`], ['Average mark', totals.averageMark.toFixed(1)], ['Overall grade', totals.grade], ['Subjects recorded', student.subjects.length]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value || 'Not provided'}</dd></div>)}</dl></section></div></div>
}